from PySide6.QtGui import QColor, Qt
from PySide6.QtWidgets import QApplication, QLineEdit, QWidget, QPushButton, QVBoxLayout, QLabel, QFrame, QTextEdit, \
    QProgressBar, QSlider, QCheckBox, QComboBox, QButtonGroup, QRadioButton, QDial, QSpinBox, QDateTimeEdit, \
    QDoubleSpinBox, QStyleFactory
from PySide6.QtCore import Slot, QDate


class Window(QWidget):
    @Slot()
    def handle_radio_buttons(self):
        print(self.group.checkedId())

    def __init__(self):
        super().__init__()
        self.setWindowTitle("Примеры виджетов")
        self.setMinimumWidth(300)
        self.setMinimumHeight(100)
        layout = QVBoxLayout()
        label = QLabel('Пример рамки')
        label.setFrameStyle(QFrame.Panel | QFrame.Sunken)
        label.setLineWidth(2)
        layout.addWidget(label)
        bar = QProgressBar()
        bar.setRange(30, 110)
        bar.setValue(50)
        bar.setTextVisible(True)
        layout.addWidget(bar)
        slider = QSlider()
        slider.setRange(-4, 38)
        slider.setOrientation(Qt.Orientation.Horizontal)
        layout.addWidget(slider)
        label = QLabel('0')
        label.setFrameStyle(QFrame.Panel | QFrame.Raised)
        label.setLineWidth(2)
        layout.addWidget(label)
        slider.sliderMoved.connect(label.setNum)
        checkBox = QCheckBox("Выбери меня!")
        layout.addWidget(checkBox)
        combo = QComboBox()
        combo.addItems(['красный', 'зеленый', 'синий'])
        layout.addWidget(combo)
        label = QLabel()
        label.setFrameStyle(QFrame.Panel | QFrame.Raised)
        label.setLineWidth(2)
        layout.addWidget(label)
        combo.currentTextChanged.connect(label.setText)
        radioRed = QRadioButton('красный')
        radioRed.setChecked(True)
        radioGreen = QRadioButton('зеленый')
        radioBlue = QRadioButton('синий')
        self.group = QButtonGroup()
        self.group.addButton(radioRed, id=1)
        self.group.addButton(radioGreen, id=2)
        self.group.addButton(radioBlue, id=3)
        layout.addWidget(radioRed)
        layout.addWidget(radioGreen)
        layout.addWidget(radioBlue)
        self.group.buttonClicked.connect(self.handle_radio_buttons)
        dial = QDial()
        dial.setNotchesVisible(True)
        dial.setRange(-50, 50)
        dial.setWrapping(False)
        layout.addWidget(dial)
        spinBox = QDoubleSpinBox()
        spinBox.setRange(-1.5, 10.5)
        spinBox.setSingleStep(0.5)
        spinBox.setSuffix(' кг')
        spinBox.setDecimals(1)
        layout.addWidget(spinBox)
        dateTimeEdit = QDateTimeEdit(QDate.currentDate())
        dateTimeEdit.setMinimumDate(QDate.currentDate().addDays(-365))
        dateTimeEdit.setMaximumDate(QDate.currentDate().addDays(365))
        dateTimeEdit.setDisplayFormat("yyyy.MM.dd hh:mm")
        dateTimeEdit.setCalendarPopup(True)
        layout.addWidget(dateTimeEdit)
        self.setLayout(layout)

if __name__ == "__main__":
    app = QApplication([])
    print(QStyleFactory.keys()) # ['windowsvista', 'Windows', 'Fusion']
    QApplication.setStyle(QStyleFactory.create("Fusion"))
    window = Window()
    window.show()
    app.exec()
